In [2]:
import numpy as np

In [3]:
# 1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

import numpy as np
arr = np.arange(6)
print(arr.dtype)

int64


In [4]:
# 2. Given a NumPy array 'arr', check if its data type is float64.

arr = np.array([1.5, 2.6, 3.7])
print(arr.dtype == np.float64)

True


In [5]:
#  3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print(arr)

[1.+2.j 3.+4.j 5.+6.j]


In [6]:
# 4. Convert an existing NumPy array 'arr' of integers to float32 data type.

arr = np.array([1, 2, 3])
arr = arr.astype(np.float32)
print(arr)

[1. 2. 3.]


In [7]:
#  5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

arr = np.array([1.23456789, 2.34567891], dtype=np.float64)
arr = arr.astype(np.float32)
print(arr)

[1.2345679 2.3456788]


In [8]:
#  6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data

def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype

arr = np.array([[1, 2], [3, 4]])
print(array_attributes(arr))

((2, 2), 4, dtype('int64'))


In [9]:
# 7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

def array_dimension(arr):
    return arr.ndim

arr = np.array([1, 2, 3])
print(array_dimension(arr))


1


In [10]:
#  8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

def item_size_info(arr):
    return arr.itemsize, arr.nbytes

arr = np.array([1, 2, 3], dtype=np.int32)
print(item_size_info(arr))


(4, 12)


In [11]:
#  9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.
def array_strides(arr):
    return arr.strides

arr = np.array([[1, 2], [3, 4]])
print(array_strides(arr))

(16, 8)


In [12]:
#  10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

def shape_stride_relationship(arr):
    return arr.shape, arr.strides

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(shape_stride_relationship(arr))

((2, 3), (24, 8))


In [13]:
# 11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.
import numpy as np

def create_zeros_array(n):
    return np.zeros(n)

print(create_zeros_array(5))

[0. 0. 0. 0. 0.]


In [14]:
# 12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

print(create_ones_matrix(3, 4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
# 13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`.
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

print(generate_range_array(1, 10, 2))

[1 3 5 7 9]


In [16]:
# 14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

print(generate_linear_space(0, 1, 5))

[0.   0.25 0.5  0.75 1.  ]


In [17]:
# 15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.
def create_identity_matrix(n):
    return np.eye(n)

print(create_identity_matrix(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
# 16. Write a function that takes a Python list and converts it into a NumPy array.
def list_to_array(py_list):
    return np.array(py_list)

print(list_to_array([1, 2, 3, 4]))

[1 2 3 4]


In [19]:
# 17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.
arr = np.array([1, 2, 3, 4])
view_arr = arr.view()
print(view_arr)

[1 2 3 4]


In [20]:
# 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.
def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(concatenate_arrays(arr1, arr2, axis=0))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [21]:
# 19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.
arr1 = np.array([[1], [2], [3]])
arr2 = np.array([[4, 5, 6]])
result = np.concatenate((arr1, arr2.T), axis=1)
print(result)

[[1 4]
 [2 5]
 [3 6]]


In [22]:
# 20. Write a function that vertically stacks multiple NumPy arrays given as a list.
def vertical_stack(arrays):
    return np.vstack(arrays)

arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
print(vertical_stack([arr1, arr2]))

[[1 2]
 [3 4]]


In [23]:
# 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.
def create_range_array(start, stop, step):
    return np.arange(start, stop + 1, step)

print(create_range_array(1, 10, 2))

[1 3 5 7 9]


In [24]:
# 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).
def generate_equally_spaced():
    return np.linspace(0, 1, 10)

print(generate_equally_spaced())

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [28]:
# 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).
def create_log_spaced():
    return np.logspace(0, 3, 5)

print(create_log_spaced())

[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [29]:
# 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.
import pandas as pd

def create_dataframe():
    data = np.random.randint(1, 101, (5, 3))
    return pd.DataFrame(data)

print(create_log_spaced())

[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [30]:
# 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.
def replace_negatives(df, column):
    df[column] = np.where(df[column] < 0, 0, df[column])
    return df

df = pd.DataFrame([[1, -2, 3], [4, -5, 6], [7, -8, 9]])
print(replace_negatives(df, 1))

   0  1  2
0  1  0  3
1  4  0  6
2  7  0  9


In [31]:
# 26. Access the 3rd element from the given NumPy array.
arr = np.array([10, 20, 30, 40, 50])
third_element = arr[2]

print(third_element)

30


In [32]:
# 27. Retrieve the element at index (1, 2) from the 2D NumPy array.
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
element = arr_2d[1, 2]

print(element)

6


In [33]:
# 28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
arr = np.array([3, 8, 2, 10, 5, 7])
elements = arr[arr > 5]

print(elements)

[ 8 10  7]


In [34]:
# 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
sliced_array = arr[2:6]

print(sliced_array)

[3 4 5 6]


In [35]:
# 30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sub_array = arr_2d[0:2, 1:3]

print(sub_array)

[[2 3]
 [5 6]]


In [36]:
# 31. Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.
def extract_elements(arr, indices):
    return arr[tuple(indices.T)]

indices = np.array([[0, 1], [1, 2]])
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(extract_elements(arr, indices))

[2 6]


In [37]:
# 32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.
def filter_elements(arr, threshold):
    return arr[arr > threshold]

print(filter_elements(arr, 5))

[6 7 8 9]


In [38]:
# 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.
def extract_3d_elements(arr, idx1, idx2, idx3):
    return arr[idx1, idx2, idx3]

arr_3d = np.random.randint(1, 10, (3, 3, 3))
idx1 = np.array([0, 1])
idx2 = np.array([0, 2])
idx3 = np.array([1, 2])
print(extract_3d_elements(arr_3d, idx1, idx2, idx3))

[1 8]


In [39]:
# 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.
def extract_with_conditions(arr, cond1, cond2):
    return arr[(cond1) & (cond2)]

cond1 = arr > 3
cond2 = arr < 8
print(extract_with_conditions(arr, cond1, cond2))

[4 5 6 7]


In [40]:
# 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.
def extract_by_indices(arr, row_indices, col_indices):
    return arr[row_indices, col_indices]

row_indices = np.array([0, 1])
col_indices = np.array([2, 1])
print(extract_by_indices(arr_2d, row_indices, col_indices))

[3 5]


In [41]:
# 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.
def add_scalar(arr):
    return arr + 5

arr_3x3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(add_scalar(arr_3x3))

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [42]:
# 37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.
def multiply_rows(arr1, arr2):
    return arr1.T * arr2

arr1 = np.array([[2, 2, 2]])
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(multiply_rows(arr1, arr2))

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [66]:
# 38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.
def add_rows(arr1, arr2):
     return arr1.T + arr2

arr1 = np.array([[1, 1, 1, 1]])
arr2 = np.array([[2, 3, 4], [5, 6, 7], [8, 9, 10], [11, 12, 13]])

print(add_rows(arr1, arr2))

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [44]:
# 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.
def add_arrays(arr1, arr2):
    return arr1 + arr2

arr1 = np.array([[1], [2], [3]])
arr2 = np.array([[4, 5, 6]])
print(add_arrays(arr1, arr2))

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [45]:
# 40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.
def multiply_incompatible(arr1, arr2):
    try:
        return arr1 * arr2
    except ValueError:
        return "Shape mismatch, cannot broadcast."

arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4, 5], [6, 7]])
print(multiply_incompatible(arr1, arr2))

Shape mismatch, cannot broadcast.


In [46]:
# 41. Calculate column-wise mean for the given array.
def column_mean(arr):
    return np.mean(arr, axis=0)

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(column_mean(arr))

[4. 5. 6.]


In [47]:
# 42. Find maximum value in each row of the given array.
def row_max(arr):
    return np.max(arr)

print(row_max(arr))

9


In [48]:
# 43. For the given array, find indices of maximum value in each column.
def column_max_indices(arr):
    return np.argmax(arr, axis=0)

print(column_max_indices(arr))

[2 2 2]


In [49]:
# 44. For the given array, apply custom function to calculate moving sum along rows.
def moving_sum(arr, window_size=2):
    return np.apply_along_axis(lambda x: np.convolve(x, np.ones(window_size, dtype=int), 'valid'), axis=1, arr=arr)

print(moving_sum(arr))

[[ 3  5]
 [ 9 11]
 [15 17]]


In [50]:
# 45. In the given array, check if all elements in each column are even.
def check_all_even(arr):
    return np.all(arr % 2 == 0, axis=0)

print(check_all_even(arr))

[False False False]


In [51]:
# 46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.
def reshape_array(arr, m, n):
    return arr.reshape(m, n)

print(reshape_array(arr, 3, 3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [52]:
# 47. Create a function that takes a matrix as input and returns the flattened array.
def flatten_matrix(matrix):
    return matrix.flatten()

print(flatten_matrix(arr))

[1 2 3 4 5 6 7 8 9]


In [53]:
# 48. Write a function that concatenates two given arrays along a specified axis.
def concatenate_arrays(arr1, arr2, axis):
    return np.concatenate((arr1, arr2), axis=axis)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(concatenate_arrays(arr1, arr2, axis=0))

[1 2 3 4 5 6]


In [54]:
# 49. Create a function that splits an array into multiple sub-arrays along a specified axis.
def split_array(arr, indices, axis):
    return np.split(arr, indices, axis=axis)

print(split_array(arr, [1], axis=0))

[array([[1, 2, 3]]), array([[4, 5, 6],
       [7, 8, 9]])]


In [55]:
# 50. Write a function that inserts and then deletes elements from a given array at specified indices.
def insert_and_delete_elements(arr, indices_to_insert, values_to_insert, indices_to_delete):
    arr = np.insert(arr, indices_to_insert, values_to_insert)
    arr = np.delete(arr, indices_to_delete)
    return arr

arr = np.array([1, 2, 3, 4])
indices_to_insert = [1, 2]
values_to_insert = [10, 20]
indices_to_delete = [3]
print(insert_and_delete_elements(arr, indices_to_insert, values_to_insert, indices_to_delete))

[ 1 10  2  3  4]


In [56]:
# 51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.
def elementwise_addition(arr1, arr2):
    return arr1 + arr2

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(elementwise_addition(arr1, arr2))

[5 7 9]


In [57]:
# 52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.
def elementwise_subtraction(arr1, arr2):
    return arr1 - arr2

arr1 = np.array([10, 9, 8])
arr2 = np.array([1, 2, 3])
print(elementwise_subtraction(arr1, arr2))

[9 7 5]


In [58]:
# 53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.
def elementwise_multiplication(arr1, arr2):
    return arr1 * arr2

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(elementwise_multiplication(arr1, arr2))

[ 4 10 18]


In [59]:
# 54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.
def elementwise_division(arr1, arr2):
    return arr1 / arr2

arr1 = np.array([10, 20, 30])
arr2 = np.array([2, 4, 6])
print(elementwise_division(arr1, arr2))

[5. 5. 5.]


In [60]:
# 55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.
def elementwise_exponentiation(arr1, arr2):
    return arr1 ** arr2

arr1 = np.array([1, 2, 3])
arr2 = np.array([3, 2, 1])
print(elementwise_exponentiation(arr1, arr2))

[1 4 3]


In [61]:
# 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
def count_substring(arr, substring):
    return np.char.count(arr, substring)

arr = np.array(["apple", "banana", "cherry", "apple", "apple"])
substring = "apple"
print(count_substring(arr, substring))

[1 0 0 1 1]


In [67]:
# 57. Write a function that extracts uppercase characters from a NumPy array of strings.
def extract_uppercase(arr):
    return np.array([''.join([char for char in s if char.isupper()]) for s in arr])

arr = np.array(["Hello", "WORLD", "Python", "NUMPY"])
print(extract_uppercase(arr))

['H' 'WORLD' 'P' 'NUMPY']


In [68]:
# 58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
def replace_substring(arr, old, new):
    return np.char.replace(arr, old, new)

arr = np.array(["apple", "banana", "cherry"])
print(replace_substring(arr, "a", "o"))

['opple' 'bonono' 'cherry']


In [69]:
# 59. Write a function that concatenates strings in a NumPy array element-wise.
def elementwise_concatenate(arr1, arr2):
    return np.char.add(arr1, arr2)

arr1 = np.array(["Hello", "Good"])
arr2 = np.array(["World", "Morning"])
print(elementwise_concatenate(arr1, arr2))

['HelloWorld' 'GoodMorning']


In [70]:
# 60. Write a function that finds the length of the longest string in a NumPy array.
def longest_string_length(arr):
    return max(np.char.str_len(arr))

arr = np.array(["apple", "banana", "cherry", "date"])
print(longest_string_length(arr))

6


In [71]:
# 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.
def compute_statistics():
    data = np.random.randint(1, 1001, size=100)
    mean = np.mean(data)
    median = np.median(data)
    variance = np.var(data)
    std_dev = np.std(data)
    return mean, median, variance, std_dev

print(compute_statistics())

(507.93, 476.5, 77206.22510000001, 277.8600818757527)


In [72]:
# 62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.
def compute_percentiles():
    data = np.random.uniform(1, 100, size=50)
    p25 = np.percentile(data, 25)
    p75 = np.percentile(data, 75)
    return p25, p75

print(compute_percentiles())

(20.22158141087839, 70.25809681306214)


In [73]:
# 63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.
def compute_correlation(arr1, arr2):
    return np.corrcoef(arr1, arr2)

arr1 = np.random.rand(10)
arr2 = np.random.rand(10)
print(compute_correlation(arr1, arr2))

[[1.         0.52293966]
 [0.52293966 1.        ]]


In [74]:
# 64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.
def matrix_multiplication(mat1, mat2):
    return np.dot(mat1, mat2)

mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
print(matrix_multiplication(mat1, mat2))

[[19 22]
 [43 50]]


In [75]:
# 65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.
def compute_multiple_percentiles():
    data = np.random.randint(10, 1001, size=50)
    p10 = np.percentile(data, 10)
    median = np.percentile(data, 50)
    p90 = np.percentile(data, 90)
    q1 = np.percentile(data, 25)
    q3 = np.percentile(data, 75)
    return p10, median, p90, q1, q3

print(compute_multiple_percentiles())

(115.5, 415.0, 827.2, 205.5, 732.0)


In [76]:
# 66. Create a NumPy array of integers and find the index of a specific element.
def find_index(arr, value):
    return np.where(arr == value)[0]

arr = np.array([10, 20, 30, 40])
print(find_index(arr, 30))

[2]


In [77]:
# 67. Generate a random NumPy array and sort it in ascending order.
def sort_array(arr):
    return np.sort(arr)

arr = np.array([30, 10, 20, 40])
print(sort_array(arr))

[10 20 30 40]


In [78]:
# 68. Filter elements >20 in the given NumPy array.
def filter_greater_than_20(arr):
    return arr[arr > 20]

arr = np.array([10, 20, 30, 40])
print(filter_greater_than_20(arr))

[30 40]


In [79]:
# 69. Filter elements which are divisible by 3 from a given NumPy array.
def filter_divisible_by_3(arr):
    return arr[arr % 3 == 0]

arr = np.array([1, 2, 3, 4, 5, 6])
print(filter_divisible_by_3(arr))

[3 6]


In [80]:
# 70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
def filter_between_20_and_40(arr):
    return arr[(arr >= 20) & (arr <= 40)]

arr = np.array([10, 20, 30, 40, 50])
print(filter_between_20_and_40(arr))

[20 30 40]


In [81]:
# 71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
def check_byte_order(arr):
    return arr.dtype.byteorder

arr = np.array([1, 2, 3])
print(check_byte_order(arr))

=


In [82]:
# 72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
def inplace_byte_swap(arr):
    arr.byteswap(inplace=True)
    return arr

arr = np.array([1, 2, 3], dtype='>i4')
print(inplace_byte_swap(arr))

[16777216 33554432 50331648]


In [83]:
# 73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.
def new_byte_order(arr):
    return arr.newbyteorder()

arr = np.array([1, 2, 3], dtype='>i4')
print(new_byte_order(arr))

[16777216 33554432 50331648]


In [84]:
# 74. For the given NumPy array, swap its byte order conditionally based on system endianness using `newbyteorder()`.
def conditional_byte_order(arr):
    if arr.dtype.byteorder == '=':
        return arr.newbyteorder()
    return arr

arr = np.array([1, 2, 3], dtype='>i4')
print(conditional_byte_order(arr))

[1 2 3]


In [85]:
# 75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.
def check_swap_necessity(arr):
    return arr.dtype.byteorder not in ('=', '|')

arr = np.array([1, 2, 3], dtype='>i4')
print(check_swap_necessity(arr))

True


In [86]:
# 76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.
def modify_copy(arr1):
    copy_arr = arr1.copy()
    copy_arr[0] = -1
    return arr1, copy_arr

arr1 = np.array([1, 2, 3, 4, 5])
print(modify_copy(arr1))

(array([1, 2, 3, 4, 5]), array([-1,  2,  3,  4,  5]))


In [87]:
# 77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.
def modify_view(matrix):
    view_slice = matrix[0:2, 0:2]
    view_slice[0, 0] = -1
    return matrix, view_slice

matrix = np.random.randint(1, 10, (3, 3))
print(modify_view(matrix))

(array([[-1,  2,  7],
       [ 2,  1,  1],
       [ 7,  6,  2]]), array([[-1,  2],
       [ 2,  1]]))


In [88]:
# 78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.
def broadcast_addition(array_a):
    view_b = array_a[:, :2]
    view_b += 5
    return array_a, view_b

array_a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(broadcast_addition(array_a))

(array([[ 6,  7,  3],
       [ 9, 10,  6],
       [12, 13,  9],
       [15, 16, 12]]), array([[ 6,  7],
       [ 9, 10],
       [12, 13],
       [15, 16]]))


In [89]:
# 79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from `orig_array`. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.
def modify_reshaped_view(orig_array):
    reshaped_view = orig_array.reshape(4, 2)
    reshaped_view[0, 0] = -1
    return orig_array, reshaped_view

orig_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(modify_reshaped_view(orig_array))

(array([[-1,  2,  3,  4],
       [ 5,  6,  7,  8]]), array([[-1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8]]))


In [90]:
# 80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.
def modify_copy_greater_than_5(data):
    data_copy = data[data > 5].copy()
    data_copy[0] = -1
    return data, data_copy

data = np.random.randint(1, 10, (3, 4))
print(modify_copy_greater_than_5(data))

(array([[8, 3, 7, 4],
       [2, 8, 5, 1],
       [1, 6, 1, 8]]), array([-1,  7,  8,  6,  8]))


In [91]:
# 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.
def add_subtract_matrices(A, B):
    return A + B, A - B

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(add_subtract_matrices(A, B))

(array([[ 6,  8],
       [10, 12]]), array([[-4, -4],
       [-4, -4]]))


In [96]:
# 82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.
def multiply_matrices(C, D):
    return np.dot(C, D)

C = np.array([[1, 2], [4, 5], [7, 8]])
D = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(multiply_matrices(C, D))

[[11 14 17 20]
 [29 38 47 56]
 [47 62 77 92]]


In [93]:
# 83. Create a matrix `E` and find its transpose.
def transpose_matrix(E):
    return E.T

E = np.array([[1, 2], [3, 4]])
print(transpose_matrix(E))

[[1 3]
 [2 4]]


In [94]:
# 84. Generate a square matrix `F` and compute its determinant.
def determinant_matrix(F):
    return np.linalg.det(F)

F = np.array([[1, 2], [3, 4]])
print(determinant_matrix(F))

-2.0000000000000004


In [95]:
# 85. Create a square matrix `G` and find its inverse.
def inverse_matrix(G):
    return np.linalg.inv(G)

G = np.array([[1, 2], [3, 4]])
print(inverse_matrix(G))

[[-2.   1. ]
 [ 1.5 -0.5]]
